### ISSUE TITLE
No Resolve References in getStory()

### ISSUE THREAD

**Issue by danielbrooks4p** [storyblok/php-client#10]
On line 272 of `src/Storyblok/Client.php`, the options are being built for us. This does not allow us to pass in options like `resolve_relations` to have global component content returned with the call to get a story.

We need a way to pass in the string of the global component to resolve when requesting a story as mentioned in this walkthrough: https://www.storyblok.com/tp/global-components-references#resolving-the-relationship-with-the-api

**Comment by danielbrooks4p** [comment]
Potential solution in this pull request: https://github.com/storyblok/php-client/pull/11

**Comment by danielbrooks4p** [comment]
@onefriendaday - Just circling back around. Any update on this? Thanks!

**Comment by ademarCardoso** [comment]
Hello @danielbrooks4p , thanks for reporting a problem :) , or the Pull Request you mentioned above has been merged 👍

**Comment by andyjaar** [comment]
I have made a similar Pull Request (#14) for getStories()

**Comment by ademarCardoso** [comment]
Hi @andyjaar Thanks to send a PR and comented at this issue, I thought the problem had been solved, let's check and if possible merge your PR, thanks :)
