### ISSUE TITLE
Allow $editModeEnabled override to be set in constructor

### ISSUE THREAD

**Issue by ibgrav** [storyblok/php-client#20]
After working with the JS storyblok client and the REST API directly, I came to expect the ?version=draft flag to be set manually (mostly by my own environment variables).

$editModeEnabled is a private variable and can only be set to true by including _storyblok in the request. I am hoping for the ability to set the $editModeEnabled in the class constructor. eg:

$client = new \Storyblok\Client('my-token', editMode: TRUE);

Alternatively, this could be set at each request, like in getStoryBySlug();

**Comment by joaokamun** [comment]
You can use `$client->editMode(true)` to enable it before a request.
