### ISSUE TITLE
PHP8 bug

### ISSUE THREAD

**Issue by schranzer235** [storyblok/php-client#21]
Hello,

thanks for providing this storyblok php client. It is very useful!

I'm afraid, since we upgraded to PHP8 we have to make a little change regarding to latest bug reports.

According to this blog post: https://php.watch/versions/8.0/deprecate-required-param-after-optional

I encounter exceptions, when using latest version of this library.

What we could change is in StoryBlok\Client, the following:

- Line 584
from private function _generateTree($parent = 0, $items),
to private function _generateTree($items, $parent = 0)

- Line 581
from return $this->_generateTree(0, $tree);
to return $this->_generateTree($tree);

- Line 597
from $this->_generateTree($item['id'], $items);
to $this->_generateTree($items, $item['id']);

And exception would be gone.

Could you fix this and tag a new release?

Thanks in advance

**Comment by Noaber** [comment]
Is there any chance that this will be fixed soon ? I see that RicLeP already opened a pull request which should fix this issue.

**Comment by christianzoppi** [comment]
Closed by #24
