### ISSUE TITLE
Request: Brach for Guzzle v6

### ISSUE THREAD

**Issue by jahvi** [storyblok/php-client#26]
Hey I maintain a [Magento 2 integration for Storyblok](https://github.com/Media-Lounge/magento2-storyblok-integration) that relies on this module to interact with the SB API.

Unfortunately Magento uses Guzzle as well but they lock it at v6, this hasn't been an issue because I've used the 1.3 version of the client but we've ran into a couple issues recently that are fixed by updating to the latest 1.5 version.

Would it be possible for you to create a branch from master that uses `"guzzlehttp/guzzle": "^6.0"` as a dependency instead? We tried creating a fork and requiring that instead but [that doesn't work](https://stackoverflow.com/a/43076062/455319).

**Comment by christianzoppi** [comment]
Resolved by #28
