### ISSUE TITLE
Does it Support Api V2 Already?

### ISSUE THREAD

**Issue by pscheit** [storyblok/php-client#32]
I constructed my client with the apiVersion as "v2"

But then I get:

resulted in a `422 Unknown` response:
{"error":"Parameter(s) cache_version not allowed"}

I am confused :) 

Am I supposed to use the old v1 ?  

I want to set the language parameter and cant see it.

Thank You!

**Comment by GerritPlehn** [comment]
Hello @pscheit :wave:
The implementation for v2 is currently undergoing review, see #31.
You are very welcome to try it out in your test-environment!

**Comment by pscheit** [comment]
oh man! I am sorry, i did check the issues but not then open PRs!
