### ISSUE TITLE
Error on Management Client

### ISSUE THREAD

**Issue by pchaudhary312** [storyblok/php-client#40]
On the latest release, there is an error on the Management Client. When trying to use the Management Client, the following error occurs: 
![image](https://user-images.githubusercontent.com/31067245/156487856-e1f5a041-5076-4436-9f7a-e0fe3699ec51.png)
The error is resolved once the responseHandler function in ManagementClient.php is updated to have same attributes as the one from BaseClient.php class.

Thanks

**Comment by christianzoppi** [comment]
Thanks @pchaudhary312 this issue has been fixed by #41
