### ISSUE TITLE
Please create a new tag with the last changes from march

### ISSUE THREAD

**Issue by dannydorfel** [storyblok/php-client#62]
End of March an MR was merged fixing the V2 language issues when requesting an story. Would be nice to not depend on dev-master to use the fixed client.

**Comment by roberto-butti** [comment]
Hi @dannydorfel  , thank you for raising this point.
There is a new release / tag: https://github.com/storyblok/php-client/releases/tag/v2.3.0

Here is the changes: https://github.com/storyblok/php-client/compare/v2.2.0...v2.3.0

The most relevant changes are:

- fix deprecation in http_build_query
- Add PHP CS Fixer
- improve the GitHub Actions for code quality tools
- fix sending language parameters (removing the additional check for uuid)
- improving the readme with resolving relations, setting the region (EU/US)

And yes this repo needs a CHANGELOG file, I'm going to create a PR  for this

**Comment by roberto-butti** [comment]
@joaokamun , I think we can close this issue because of the release: https://github.com/storyblok/php-client/releases/tag/v2.3.0
