### ISSUE TITLE
Why is this repository so neglected? Is contribution still appreciated?

### ISSUE THREAD

**Issue by web-dev-passion** [storyblok/php-client#64]
I created a [pull request](https://github.com/storyblok/php-client/pull/61 ) on Sep 16 2022 and it did not receive even any feedback. The PHP Storyblok Clients lacks so many features that the [NodeJS implementation ](https://github.com/storyblok/storyblok-js-client) provides.

If this project is abandoned, a notice about this would be 'great' to see. It is so frustating trying to improve the repository by contributing only to see that the repository seems to be neglected.

Please note that this criticism is not meant to blame you. You have probably a lot of tasks and I do not want to complain about how long it takes for a PR to be managed. Instead I just want to clarify if further effort by users is appreciated and likely to be considered by the respective persons.

**Comment by roberto-butti** [comment]
Hi @web-dev-passion , I'm talking internally about how to improve this repo (I'm pretty new in the Storyblok team, so it is the reason why I'm aligning internally, but I'm a PHP addict and lover).
I think this repo is valuable to the PHP community and also to the product. So thank you for your patience, if you have any suggestions please keep sharing them and, I am going to test your PR.

**Comment by web-dev-passion** [comment]
Thats great to hear @roberto-butti. Thank you for your input!
Hopefully you find your way into the new team easily 😉

**Comment by roberto-butti** [comment]
Yes @web-dev-passion  if you agree, we can close this issue and switch to the PR thread (your getAll PR). i have some specific comments on that.
